[package]
name = "tmq"
version = "0.2.1"
authors = ["cetra3 <cetra3@hotmail.com>", "skrap <jonah@petri.us>", "kobzol <berykubik@gmail.com>"]
license = "MIT/Apache-2.0"
description = "ZeroMQ bindings for Tokio"
repository = "https://github.com/cetra3/tmq"
readme = "README.md"
edition = "2018"

[features]
zmq-vendored = ["zmq/vendored"]

[dependencies]
bytes = "0.5"
futures = "0.3"
tokio = { version = "0.3.2", features = ["net"] }
mio = "0.7"
zmq = ">=0.9.2"
log = "0.4"
thiserror = "1"

[dev-dependencies]
tokio = { version = "0.3.2", features = ["full"] }
pretty_env_logger = "0.2"
rand = "0.7"
criterion = "0.3"

[[bench]]
name = "poll"
harness = false
